/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.eldoraludo.ppafgestion.util.*;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import com.eldoraludo.ppafgestion.domain.Membreppaf;

/**
 * Basic tests for Lieudestockage
 */
@SuppressWarnings("unused")
public class LieudestockageTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Lieudestockage model = new Lieudestockage();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        Lieudestockage model = new Lieudestockage();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Lieudestockage.membreppafresponsableId ==> Membreppaf.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setMembreppafresponsable() {
        Lieudestockage many = new Lieudestockage();

        // init
        Membreppaf one = new Membreppaf();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setMembreppafresponsable(one);

        // make sure it is propagated properly
        assertNotNull(many.getMembreppafresponsableId());
        assertEquals(one, many.getMembreppafresponsable());
        assertSame(many.getMembreppafresponsableId(), one.getId());
        // now set it to back to null
        many.setMembreppafresponsable(null);

        // make sure null is propagated properly
        assertNull(many.getMembreppafresponsable());

        // make sure it is propagated on fk column as well
        assertNull(many.getMembreppafresponsableId());
    }

    @Test
    public void toStringNotNull() {
        Lieudestockage model = new Lieudestockage();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Lieudestockage model1 = new Lieudestockage();
        Lieudestockage model2 = new Lieudestockage();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setRue("a");
        model2.setRue("a");

        model1.setVille("a");
        model2.setVille("a");

        model1.setCodepostal("a");
        model2.setCodepostal("a");

        model1.setInfosuppl("a");
        model2.setInfosuppl("a");

        model1.setNote("a");
        model2.setNote("a");
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}