/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.eldoraludo.ppafgestion.util.*;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.domain.Role;

/**
 * Basic tests for Utilisateur
 */
@SuppressWarnings("unused")
public class UtilisateurTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Utilisateur model = new Utilisateur();
        assertFalse(model.isIdSet());
    }

    @Test
    public void isIdSetReturnsTrue() {
        Utilisateur model = new Utilisateur();
        model.setId(ValueGenerator.getUniqueInteger());
        assertNotNull(model.getId());
        assertTrue(model.isIdSet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Many to One:  Utilisateur.membreppafId ==> Membreppaf.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setMembreppaf() {
        Utilisateur many = new Utilisateur();

        // init
        Membreppaf one = new Membreppaf();

        one.setId(ValueGenerator.getUniqueInteger());
        many.setMembreppaf(one);

        // make sure it is propagated properly
        assertNotNull(many.getMembreppafId());
        assertEquals(one, many.getMembreppaf());
        assertSame(many.getMembreppafId(), one.getId());
        // now set it to back to null
        many.setMembreppaf(null);

        // make sure null is propagated properly
        assertNull(many.getMembreppaf());

        // make sure it is propagated on fk column as well
        assertNull(many.getMembreppafId());
    }

    //-------------------------------------------------------------
    // Pure Many to Many
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void manyToMany_addRole() {
        Utilisateur many1 = new Utilisateur();
        Role many2 = new Role();

        // add it
        many1.addRole(many2);

        // check it is propagated
        assertTrue(many1.containsRole(many2));
        // now let's remove it
        many1.removeRole(many2);

        // check it is propagated
        assertFalse(many1.containsRole(many2));
    }

    @Test
    public void toStringNotNull() {
        Utilisateur model = new Utilisateur();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        Utilisateur model1 = new Utilisateur();
        Utilisateur model2 = new Utilisateur();

        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);

        model1.setUsername("aaaa");
        model2.setUsername("aaaa");

        model1.setPassword("a");
        model2.setPassword("a");

        model1.setEmail("dummy@dummy.com");
        model2.setEmail("dummy@dummy.com");

        model1.setRue("a");
        model2.setRue("a");

        model1.setVille("a");
        model2.setVille("a");

        model1.setCodepostal("a");
        model2.setCodepostal("a");

        model1.setInfosuppl("a");
        model2.setInfosuppl("a");

        model1.setActif(true);
        model2.setActif(true);
        assertTrue(model1.isIdSet());
        assertTrue(model2.isIdSet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}