/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.dao.support.PropertySelectors.BooleanSelector.newBooleanSelector;
import static com.eldoraludo.ppafgestion.domain.Contact_.actif;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.dao.support.PropertySelectors.BooleanSelector;
import com.eldoraludo.ppafgestion.domain.Contact;
import com.eldoraludo.ppafgestion.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for contact search.
 */
@Component
@Scope("session")
public class ContactSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Contact contact = new Contact();
    private BooleanSelector<Contact> actifSelector = newBooleanSelector(actif);

    public Contact getContact() {
        return contact;
    }

    // Selectors for property
    public BooleanSelector<Contact> getActifSelector() {
        return actifSelector;
    }
}