/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.repository.ItemlieudestockageRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.ItemlieudestockageConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class ItemlieudestockageController {
    private static final long serialVersionUID = 1L;

    @Inject
    private ItemlieudestockageRepository itemlieudestockageRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private ItemlieudestockageConverter itemlieudestockageConverter;

    public Itemlieudestockage newIfNull(Itemlieudestockage itemlieudestockage) {
        if (itemlieudestockage != null) {
            return itemlieudestockage;
        }

        return itemlieudestockageRepository.getNewWithDefaults();
    }

    public boolean save(Itemlieudestockage itemlieudestockage) {
        itemlieudestockageRepository.save(itemlieudestockage);
        messageUtil.info("status_saved_ok", itemlieudestockageConverter.print(itemlieudestockage));
        return true;
    }

    public boolean saveAndClose(Itemlieudestockage itemlieudestockage) {
        itemlieudestockageRepository.save(itemlieudestockage);
        messageUtil.infoDelayed("status_saved_ok", itemlieudestockageConverter.print(itemlieudestockage));
        forceClose();
        return true;
    }

    public boolean delete(Itemlieudestockage itemlieudestockage) {
        String infoArg = itemlieudestockageConverter.print(itemlieudestockage);
        itemlieudestockageRepository.delete(itemlieudestockage);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}