/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Item;
import com.eldoraludo.ppafgestion.repository.ItemRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.ItemConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class ItemController {
    private static final long serialVersionUID = 1L;

    @Inject
    private ItemRepository itemRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private ItemConverter itemConverter;

    public Item newIfNull(Item item) {
        if (item != null) {
            return item;
        }

        return itemRepository.getNewWithDefaults();
    }

    public boolean save(Item item) {
        itemRepository.save(item);
        messageUtil.info("status_saved_ok", itemConverter.print(item));
        return true;
    }

    public boolean saveAndClose(Item item) {
        itemRepository.save(item);
        messageUtil.infoDelayed("status_saved_ok", itemConverter.print(item));
        forceClose();
        return true;
    }

    public boolean delete(Item item) {
        String infoArg = itemConverter.print(item);
        itemRepository.delete(item);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}