/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ItemSelector.newItemSelector;
import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.LieudestockageSelector.newLieudestockageSelector;
import static com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate.newRangeDate;
import static com.eldoraludo.ppafgestion.dao.support.Ranges.RangeInteger.newRangeInteger;
import static com.eldoraludo.ppafgestion.domain.Itemlieudestockage_.date;
import static com.eldoraludo.ppafgestion.domain.Itemlieudestockage_.itemId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudestockage_.lieudestockageId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudestockage_.quantite;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ItemSelector;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.LieudestockageSelector;
import com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate;
import com.eldoraludo.ppafgestion.dao.support.Ranges.RangeInteger;
import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for itemlieudestockage search.
 */
@Component
@Scope("session")
public class ItemlieudestockageSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Itemlieudestockage itemlieudestockage = new Itemlieudestockage();
    private RangeDate<Itemlieudestockage> dateRange = newRangeDate(date);
    private RangeInteger<Itemlieudestockage> quantiteRange = newRangeInteger(quantite);
    private LieudestockageSelector<Itemlieudestockage> lieudestockageSelector = newLieudestockageSelector(lieudestockageId);
    private ItemSelector<Itemlieudestockage> itemSelector = newItemSelector(itemId);

    public Itemlieudestockage getItemlieudestockage() {
        return itemlieudestockage;
    }

    // Ranges, used from the view.
    public RangeDate<Itemlieudestockage> getDateRange() {
        return dateRange;
    }

    public RangeInteger<Itemlieudestockage> getQuantiteRange() {
        return quantiteRange;
    }

    // Selectors for x-to-one associations
    public LieudestockageSelector<Itemlieudestockage> getLieudestockageSelector() {
        return lieudestockageSelector;
    }

    public ItemSelector<Itemlieudestockage> getItemSelector() {
        return itemSelector;
    }
}