/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ContactSelector.newContactSelector;
import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ItemSelector.newItemSelector;
import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.LieudedepotSelector.newLieudedepotSelector;
import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate.newRangeDate;
import static com.eldoraludo.ppafgestion.dao.support.Ranges.RangeInteger.newRangeInteger;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.contactId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.date;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.itemId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.lieudedepotId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.membreppafId;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.prixunitaire;
import static com.eldoraludo.ppafgestion.domain.Itemlieudedepot_.quantite;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ContactSelector;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ItemSelector;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.LieudedepotSelector;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate;
import com.eldoraludo.ppafgestion.dao.support.Ranges.RangeInteger;
import com.eldoraludo.ppafgestion.domain.Itemlieudedepot;
import com.eldoraludo.ppafgestion.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for itemlieudedepot search.
 */
@Component
@Scope("session")
public class ItemlieudedepotSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Itemlieudedepot itemlieudedepot = new Itemlieudedepot();
    private RangeDate<Itemlieudedepot> dateRange = newRangeDate(date);
    private RangeInteger<Itemlieudedepot> quantiteRange = newRangeInteger(quantite);
    private RangeInteger<Itemlieudedepot> prixunitaireRange = newRangeInteger(prixunitaire);
    private MembreppafSelector<Itemlieudedepot> membreppafSelector = newMembreppafSelector(membreppafId);
    private ItemSelector<Itemlieudedepot> itemSelector = newItemSelector(itemId);
    private LieudedepotSelector<Itemlieudedepot> lieudedepotSelector = newLieudedepotSelector(lieudedepotId);
    private ContactSelector<Itemlieudedepot> contactSelector = newContactSelector(contactId);

    public Itemlieudedepot getItemlieudedepot() {
        return itemlieudedepot;
    }

    // Ranges, used from the view.
    public RangeDate<Itemlieudedepot> getDateRange() {
        return dateRange;
    }

    public RangeInteger<Itemlieudedepot> getQuantiteRange() {
        return quantiteRange;
    }

    public RangeInteger<Itemlieudedepot> getPrixunitaireRange() {
        return prixunitaireRange;
    }

    // Selectors for x-to-one associations
    public MembreppafSelector<Itemlieudedepot> getMembreppafSelector() {
        return membreppafSelector;
    }

    public ItemSelector<Itemlieudedepot> getItemSelector() {
        return itemSelector;
    }

    public LieudedepotSelector<Itemlieudedepot> getLieudedepotSelector() {
        return lieudedepotSelector;
    }

    public ContactSelector<Itemlieudedepot> getContactSelector() {
        return contactSelector;
    }
}