/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Lieudedepot;
import com.eldoraludo.ppafgestion.repository.LieudedepotRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.LieudedepotConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class LieudedepotController {
    private static final long serialVersionUID = 1L;

    @Inject
    private LieudedepotRepository lieudedepotRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private LieudedepotConverter lieudedepotConverter;

    public Lieudedepot newIfNull(Lieudedepot lieudedepot) {
        if (lieudedepot != null) {
            return lieudedepot;
        }

        return lieudedepotRepository.getNewWithDefaults();
    }

    public boolean save(Lieudedepot lieudedepot) {
        lieudedepotRepository.save(lieudedepot);
        messageUtil.info("status_saved_ok", lieudedepotConverter.print(lieudedepot));
        return true;
    }

    public boolean saveAndClose(Lieudedepot lieudedepot) {
        lieudedepotRepository.save(lieudedepot);
        messageUtil.infoDelayed("status_saved_ok", lieudedepotConverter.print(lieudedepot));
        forceClose();
        return true;
    }

    public boolean delete(Lieudedepot lieudedepot) {
        String infoArg = lieudedepotConverter.print(lieudedepot);
        lieudedepotRepository.delete(lieudedepot);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}