/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafgestion.domain.Lieudestockage_.membreppafresponsableId;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for lieudestockage search.
 */
@Component
@Scope("session")
public class LieudestockageSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Lieudestockage lieudestockage = new Lieudestockage();
    private MembreppafSelector<Lieudestockage> membreppafresponsableSelector = newMembreppafSelector(membreppafresponsableId);

    public Lieudestockage getLieudestockage() {
        return lieudestockage;
    }

    // Selectors for x-to-one associations
    public MembreppafSelector<Lieudestockage> getMembreppafresponsableSelector() {
        return membreppafresponsableSelector;
    }
}