/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.repository.MembreppafRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.MembreppafConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class MembreppafController {
    private static final long serialVersionUID = 1L;

    @Inject
    private MembreppafRepository membreppafRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private MembreppafConverter membreppafConverter;

    public Membreppaf newIfNull(Membreppaf membreppaf) {
        if (membreppaf != null) {
            return membreppaf;
        }

        return membreppafRepository.getNewWithDefaults();
    }

    public boolean save(Membreppaf membreppaf) {
        membreppafRepository.save(membreppaf);
        messageUtil.info("status_saved_ok", membreppafConverter.print(membreppaf));
        return true;
    }

    public boolean saveAndClose(Membreppaf membreppaf) {
        membreppafRepository.save(membreppaf);
        messageUtil.infoDelayed("status_saved_ok", membreppafConverter.print(membreppaf));
        forceClose();
        return true;
    }

    public boolean delete(Membreppaf membreppaf) {
        String infoArg = membreppafConverter.print(membreppaf);
        membreppafRepository.delete(membreppaf);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}