/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Rolemembre;
import com.eldoraludo.ppafgestion.repository.RolemembreRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.RolemembreConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class RolemembreController {
    private static final long serialVersionUID = 1L;

    @Inject
    private RolemembreRepository rolemembreRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private RolemembreConverter rolemembreConverter;

    public Rolemembre newIfNull(Rolemembre rolemembre) {
        if (rolemembre != null) {
            return rolemembre;
        }

        return rolemembreRepository.getNewWithDefaults();
    }

    public boolean save(Rolemembre rolemembre) {
        rolemembreRepository.save(rolemembre);
        messageUtil.info("status_saved_ok", rolemembreConverter.print(rolemembre));
        return true;
    }

    public boolean saveAndClose(Rolemembre rolemembre) {
        rolemembreRepository.save(rolemembre);
        messageUtil.infoDelayed("status_saved_ok", rolemembreConverter.print(rolemembre));
        forceClose();
        return true;
    }

    public boolean delete(Rolemembre rolemembre) {
        String infoArg = rolemembreConverter.print(rolemembre);
        rolemembreRepository.delete(rolemembre);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}