/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/SearchForm.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ContactSelector.newContactSelector;
import static com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector.newMembreppafSelector;
import static com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate.newRangeDate;
import static com.eldoraludo.ppafgestion.domain.Suivicontact_.contactId;
import static com.eldoraludo.ppafgestion.domain.Suivicontact_.date;
import static com.eldoraludo.ppafgestion.domain.Suivicontact_.dateprochainappel;
import static com.eldoraludo.ppafgestion.domain.Suivicontact_.membreppafId;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.ContactSelector;
import com.eldoraludo.ppafgestion.dao.support.EntitySelectors.MembreppafSelector;
import com.eldoraludo.ppafgestion.dao.support.Ranges.RangeDate;
import com.eldoraludo.ppafgestion.domain.Suivicontact;
import com.eldoraludo.ppafgestion.web.domain.support.SearchFormBase;

/**
 * Simple parameters holder for suivicontact search.
 */
@Component
@Scope("session")
public class SuivicontactSearchForm extends SearchFormBase {
    private static final long serialVersionUID = 1L;

    private Suivicontact suivicontact = new Suivicontact();
    private RangeDate<Suivicontact> dateRange = newRangeDate(date);
    private RangeDate<Suivicontact> dateprochainappelRange = newRangeDate(dateprochainappel);
    private MembreppafSelector<Suivicontact> membreppafSelector = newMembreppafSelector(membreppafId);
    private ContactSelector<Suivicontact> contactSelector = newContactSelector(contactId);

    public Suivicontact getSuivicontact() {
        return suivicontact;
    }

    // Ranges, used from the view.
    public RangeDate<Suivicontact> getDateRange() {
        return dateRange;
    }

    public RangeDate<Suivicontact> getDateprochainappelRange() {
        return dateprochainappelRange;
    }

    // Selectors for x-to-one associations
    public MembreppafSelector<Suivicontact> getMembreppafSelector() {
        return membreppafSelector;
    }

    public ContactSelector<Suivicontact> getContactSelector() {
        return contactSelector;
    }
}