/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Suivicontact;
import com.eldoraludo.ppafgestion.repository.SuivicontactRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.SuivicontactConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class SuivicontactController {
    private static final long serialVersionUID = 1L;

    @Inject
    private SuivicontactRepository suivicontactRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private SuivicontactConverter suivicontactConverter;

    public Suivicontact newIfNull(Suivicontact suivicontact) {
        if (suivicontact != null) {
            return suivicontact;
        }

        return suivicontactRepository.getNewWithDefaults();
    }

    public boolean save(Suivicontact suivicontact) {
        suivicontactRepository.save(suivicontact);
        messageUtil.info("status_saved_ok", suivicontactConverter.print(suivicontact));
        return true;
    }

    public boolean saveAndClose(Suivicontact suivicontact) {
        suivicontactRepository.save(suivicontact);
        messageUtil.infoDelayed("status_saved_ok", suivicontactConverter.print(suivicontact));
        forceClose();
        return true;
    }

    public boolean delete(Suivicontact suivicontact) {
        String infoArg = suivicontactConverter.print(suivicontact);
        suivicontactRepository.delete(suivicontact);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}