/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.domain;

import static com.eldoraludo.ppafgestion.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.domain.Utilisateur;
import com.eldoraludo.ppafgestion.repository.UtilisateurRepository;
import com.eldoraludo.ppafgestion.web.converter.domain.UtilisateurConverter;
import com.eldoraludo.ppafgestion.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class UtilisateurController {
    private static final long serialVersionUID = 1L;

    @Inject
    private UtilisateurRepository utilisateurRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private UtilisateurConverter utilisateurConverter;

    public Utilisateur newIfNull(Utilisateur utilisateur) {
        if (utilisateur != null) {
            return utilisateur;
        }

        return utilisateurRepository.getNewWithDefaults();
    }

    public boolean save(Utilisateur utilisateur) {
        utilisateurRepository.save(utilisateur);
        messageUtil.info("status_saved_ok", utilisateurConverter.print(utilisateur));
        return true;
    }

    public boolean saveAndClose(Utilisateur utilisateur) {
        utilisateurRepository.save(utilisateur);
        messageUtil.infoDelayed("status_saved_ok", utilisateurConverter.print(utilisateur));
        forceClose();
        return true;
    }

    public boolean delete(Utilisateur utilisateur) {
        String infoArg = utilisateurConverter.print(utilisateur);
        utilisateurRepository.delete(utilisateur);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}