/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Contact;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class ContactGenerator {

    /**
     * Returns a new Contact instance filled with random values.
     */
    public Contact getContact() {
        Contact contact = new Contact();

        // simple attributes follows
        contact.setNom("a");
        contact.setPrenom("a");
        contact.setNumerotelephone1("a");
        contact.setNumerotelephone2("a");
        contact.setEmail("dummy@dummy.com");
        contact.setActif(true);
        contact.setNote("a");
        contact.setRue("a");
        contact.setVille("a");
        contact.setCodepostal("a");
        contact.setInfosuppl("a");
        return contact;
    }

}