/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Item;
import com.eldoraludo.ppafgestion.repository.ItemRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.ItemDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on ItemRepositoryImpl
 */
public class ItemRepositoryImplTest {

    private ItemRepositoryImpl itemRepositoryImpl;
    private ItemDao itemDao;

    @Before
    public void setUp() {
        // called before each test.
        itemRepositoryImpl = new ItemRepositoryImpl();
        itemDao = mock(ItemDao.class);
        itemRepositoryImpl.setItemDao(itemDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Item none = null;

        when(itemDao.findUniqueOrNone(any(Item.class), any(SearchParameters.class))).thenReturn(none);

        Item result = itemRepositoryImpl.findUniqueOrNone(new Item());

        assertThat(result).isNull();
        verify(itemDao, times(1)).findUniqueOrNone(any(Item.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Item unique = new Item();

        when(itemDao.findUniqueOrNone(any(Item.class), any(SearchParameters.class))).thenReturn(unique);

        Item result = itemRepositoryImpl.findUniqueOrNone(new Item());

        assertThat(result).isNotNull();
        verify(itemDao, times(1)).findUniqueOrNone(any(Item.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(itemDao.findUniqueOrNone(any(Item.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemRepositoryImpl.findUniqueOrNone(new Item());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(itemDao.findUnique(any(Item.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        itemRepositoryImpl.findUnique(new Item());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Item unique = new Item();

        when(itemDao.findUnique(any(Item.class), any(SearchParameters.class))).thenReturn(unique);

        Item result = itemRepositoryImpl.findUnique(new Item());

        assertThat(result).isNotNull();
        verify(itemDao, times(1)).findUnique(any(Item.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(itemDao.findUnique(any(Item.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemRepositoryImpl.findUnique(new Item());
    }
}