/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.repository.ItemlieudestockageRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.ItemlieudestockageDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on ItemlieudestockageRepositoryImpl
 */
public class ItemlieudestockageRepositoryImplTest {

    private ItemlieudestockageRepositoryImpl itemlieudestockageRepositoryImpl;
    private ItemlieudestockageDao itemlieudestockageDao;

    @Before
    public void setUp() {
        // called before each test.
        itemlieudestockageRepositoryImpl = new ItemlieudestockageRepositoryImpl();
        itemlieudestockageDao = mock(ItemlieudestockageDao.class);
        itemlieudestockageRepositoryImpl.setItemlieudestockageDao(itemlieudestockageDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Itemlieudestockage none = null;

        when(itemlieudestockageDao.findUniqueOrNone(any(Itemlieudestockage.class), any(SearchParameters.class))).thenReturn(none);

        Itemlieudestockage result = itemlieudestockageRepositoryImpl.findUniqueOrNone(new Itemlieudestockage());

        assertThat(result).isNull();
        verify(itemlieudestockageDao, times(1)).findUniqueOrNone(any(Itemlieudestockage.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Itemlieudestockage unique = new Itemlieudestockage();

        when(itemlieudestockageDao.findUniqueOrNone(any(Itemlieudestockage.class), any(SearchParameters.class))).thenReturn(unique);

        Itemlieudestockage result = itemlieudestockageRepositoryImpl.findUniqueOrNone(new Itemlieudestockage());

        assertThat(result).isNotNull();
        verify(itemlieudestockageDao, times(1)).findUniqueOrNone(any(Itemlieudestockage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(itemlieudestockageDao.findUniqueOrNone(any(Itemlieudestockage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemlieudestockageRepositoryImpl.findUniqueOrNone(new Itemlieudestockage());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(itemlieudestockageDao.findUnique(any(Itemlieudestockage.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        itemlieudestockageRepositoryImpl.findUnique(new Itemlieudestockage());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Itemlieudestockage unique = new Itemlieudestockage();

        when(itemlieudestockageDao.findUnique(any(Itemlieudestockage.class), any(SearchParameters.class))).thenReturn(unique);

        Itemlieudestockage result = itemlieudestockageRepositoryImpl.findUnique(new Itemlieudestockage());

        assertThat(result).isNotNull();
        verify(itemlieudestockageDao, times(1)).findUnique(any(Itemlieudestockage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(itemlieudestockageDao.findUnique(any(Itemlieudestockage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemlieudestockageRepositoryImpl.findUnique(new Itemlieudestockage());
    }
}