/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Itemlieudedepot;
import com.eldoraludo.ppafgestion.repository.ItemlieudedepotRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.ItemlieudedepotDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on ItemlieudedepotRepositoryImpl
 */
public class ItemlieudedepotRepositoryImplTest {

    private ItemlieudedepotRepositoryImpl itemlieudedepotRepositoryImpl;
    private ItemlieudedepotDao itemlieudedepotDao;

    @Before
    public void setUp() {
        // called before each test.
        itemlieudedepotRepositoryImpl = new ItemlieudedepotRepositoryImpl();
        itemlieudedepotDao = mock(ItemlieudedepotDao.class);
        itemlieudedepotRepositoryImpl.setItemlieudedepotDao(itemlieudedepotDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Itemlieudedepot none = null;

        when(itemlieudedepotDao.findUniqueOrNone(any(Itemlieudedepot.class), any(SearchParameters.class))).thenReturn(none);

        Itemlieudedepot result = itemlieudedepotRepositoryImpl.findUniqueOrNone(new Itemlieudedepot());

        assertThat(result).isNull();
        verify(itemlieudedepotDao, times(1)).findUniqueOrNone(any(Itemlieudedepot.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Itemlieudedepot unique = new Itemlieudedepot();

        when(itemlieudedepotDao.findUniqueOrNone(any(Itemlieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Itemlieudedepot result = itemlieudedepotRepositoryImpl.findUniqueOrNone(new Itemlieudedepot());

        assertThat(result).isNotNull();
        verify(itemlieudedepotDao, times(1)).findUniqueOrNone(any(Itemlieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(itemlieudedepotDao.findUniqueOrNone(any(Itemlieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemlieudedepotRepositoryImpl.findUniqueOrNone(new Itemlieudedepot());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(itemlieudedepotDao.findUnique(any(Itemlieudedepot.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        itemlieudedepotRepositoryImpl.findUnique(new Itemlieudedepot());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Itemlieudedepot unique = new Itemlieudedepot();

        when(itemlieudedepotDao.findUnique(any(Itemlieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Itemlieudedepot result = itemlieudedepotRepositoryImpl.findUnique(new Itemlieudedepot());

        assertThat(result).isNotNull();
        verify(itemlieudedepotDao, times(1)).findUnique(any(Itemlieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(itemlieudedepotDao.findUnique(any(Itemlieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        itemlieudedepotRepositoryImpl.findUnique(new Itemlieudedepot());
    }
}