/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import java.util.Date;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Item;
import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.repository.ItemGenerator;
import com.eldoraludo.ppafgestion.repository.ItemRepository;
import com.eldoraludo.ppafgestion.repository.LieudestockageGenerator;
import com.eldoraludo.ppafgestion.repository.LieudestockageRepository;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class ItemlieudestockageGenerator {

    /**
     * Returns a new Itemlieudestockage instance filled with random values.
     */
    public Itemlieudestockage getItemlieudestockage() {
        Itemlieudestockage itemlieudestockage = new Itemlieudestockage();

        // simple attributes follows
        itemlieudestockage.setDate(new Date());
        itemlieudestockage.setQuantite(1);
        itemlieudestockage.setNote("a");
        // mandatory relation
        Lieudestockage lieudestockage = lieudestockageGenerator.getLieudestockage();
        lieudestockageRepository.save(lieudestockage);
        itemlieudestockage.setLieudestockage(lieudestockage);
        // mandatory relation
        Item item = itemGenerator.getItem();
        itemRepository.save(item);
        itemlieudestockage.setItem(item);
        return itemlieudestockage;
    }

    @Inject
    private LieudestockageRepository lieudestockageRepository;
    @Inject
    private LieudestockageGenerator lieudestockageGenerator;
    @Inject
    private ItemRepository itemRepository;
    @Inject
    private ItemGenerator itemGenerator;
}