/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Lieudedepot;
import com.eldoraludo.ppafgestion.repository.LieudedepotRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.LieudedepotDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on LieudedepotRepositoryImpl
 */
public class LieudedepotRepositoryImplTest {

    private LieudedepotRepositoryImpl lieudedepotRepositoryImpl;
    private LieudedepotDao lieudedepotDao;

    @Before
    public void setUp() {
        // called before each test.
        lieudedepotRepositoryImpl = new LieudedepotRepositoryImpl();
        lieudedepotDao = mock(LieudedepotDao.class);
        lieudedepotRepositoryImpl.setLieudedepotDao(lieudedepotDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Lieudedepot none = null;

        when(lieudedepotDao.findUniqueOrNone(any(Lieudedepot.class), any(SearchParameters.class))).thenReturn(none);

        Lieudedepot result = lieudedepotRepositoryImpl.findUniqueOrNone(new Lieudedepot());

        assertThat(result).isNull();
        verify(lieudedepotDao, times(1)).findUniqueOrNone(any(Lieudedepot.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Lieudedepot unique = new Lieudedepot();

        when(lieudedepotDao.findUniqueOrNone(any(Lieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Lieudedepot result = lieudedepotRepositoryImpl.findUniqueOrNone(new Lieudedepot());

        assertThat(result).isNotNull();
        verify(lieudedepotDao, times(1)).findUniqueOrNone(any(Lieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(lieudedepotDao.findUniqueOrNone(any(Lieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        lieudedepotRepositoryImpl.findUniqueOrNone(new Lieudedepot());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(lieudedepotDao.findUnique(any(Lieudedepot.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        lieudedepotRepositoryImpl.findUnique(new Lieudedepot());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Lieudedepot unique = new Lieudedepot();

        when(lieudedepotDao.findUnique(any(Lieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Lieudedepot result = lieudedepotRepositoryImpl.findUnique(new Lieudedepot());

        assertThat(result).isNotNull();
        verify(lieudedepotDao, times(1)).findUnique(any(Lieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(lieudedepotDao.findUnique(any(Lieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        lieudedepotRepositoryImpl.findUnique(new Lieudedepot());
    }
}