/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.repository.MembreppafGenerator;
import com.eldoraludo.ppafgestion.repository.MembreppafRepository;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class LieudestockageGenerator {

    /**
     * Returns a new Lieudestockage instance filled with random values.
     */
    public Lieudestockage getLieudestockage() {
        Lieudestockage lieudestockage = new Lieudestockage();

        // simple attributes follows
        lieudestockage.setRue("a");
        lieudestockage.setVille("a");
        lieudestockage.setCodepostal("a");
        lieudestockage.setInfosuppl("a");
        lieudestockage.setNote("a");
        // mandatory relation
        Membreppaf membreppafresponsable = membreppafGenerator.getMembreppaf();
        membreppafRepository.save(membreppafresponsable);
        lieudestockage.setMembreppafresponsable(membreppafresponsable);
        return lieudestockage;
    }

    @Inject
    private MembreppafRepository membreppafRepository;
    @Inject
    private MembreppafGenerator membreppafGenerator;
}