/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.repository.LieudestockageRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.LieudestockageDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on LieudestockageRepositoryImpl
 */
public class LieudestockageRepositoryImplTest {

    private LieudestockageRepositoryImpl lieudestockageRepositoryImpl;
    private LieudestockageDao lieudestockageDao;

    @Before
    public void setUp() {
        // called before each test.
        lieudestockageRepositoryImpl = new LieudestockageRepositoryImpl();
        lieudestockageDao = mock(LieudestockageDao.class);
        lieudestockageRepositoryImpl.setLieudestockageDao(lieudestockageDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Lieudestockage none = null;

        when(lieudestockageDao.findUniqueOrNone(any(Lieudestockage.class), any(SearchParameters.class))).thenReturn(none);

        Lieudestockage result = lieudestockageRepositoryImpl.findUniqueOrNone(new Lieudestockage());

        assertThat(result).isNull();
        verify(lieudestockageDao, times(1)).findUniqueOrNone(any(Lieudestockage.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Lieudestockage unique = new Lieudestockage();

        when(lieudestockageDao.findUniqueOrNone(any(Lieudestockage.class), any(SearchParameters.class))).thenReturn(unique);

        Lieudestockage result = lieudestockageRepositoryImpl.findUniqueOrNone(new Lieudestockage());

        assertThat(result).isNotNull();
        verify(lieudestockageDao, times(1)).findUniqueOrNone(any(Lieudestockage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(lieudestockageDao.findUniqueOrNone(any(Lieudestockage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        lieudestockageRepositoryImpl.findUniqueOrNone(new Lieudestockage());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(lieudestockageDao.findUnique(any(Lieudestockage.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        lieudestockageRepositoryImpl.findUnique(new Lieudestockage());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Lieudestockage unique = new Lieudestockage();

        when(lieudestockageDao.findUnique(any(Lieudestockage.class), any(SearchParameters.class))).thenReturn(unique);

        Lieudestockage result = lieudestockageRepositoryImpl.findUnique(new Lieudestockage());

        assertThat(result).isNotNull();
        verify(lieudestockageDao, times(1)).findUnique(any(Lieudestockage.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(lieudestockageDao.findUnique(any(Lieudestockage.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        lieudestockageRepositoryImpl.findUnique(new Lieudestockage());
    }
}