/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.domain.Rolemembre;
import com.eldoraludo.ppafgestion.repository.RolemembreGenerator;
import com.eldoraludo.ppafgestion.repository.RolemembreRepository;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class MembreppafGenerator {

    /**
     * Returns a new Membreppaf instance filled with random values.
     */
    public Membreppaf getMembreppaf() {
        Membreppaf membreppaf = new Membreppaf();

        // simple attributes follows
        membreppaf.setNom("a");
        membreppaf.setPrenom("a");
        membreppaf.setNumerotelephone1("a");
        membreppaf.setNumerotelephone2("a");
        membreppaf.setEmail("dummy@dummy.com");
        membreppaf.setActif(true);
        membreppaf.setNote("a");
        membreppaf.setRue("a");
        membreppaf.setVille("a");
        membreppaf.setCodepostal("a");
        membreppaf.setInfosuppl("a");
        // mandatory relation
        Rolemembre rolemembre = rolemembreGenerator.getRolemembre();
        rolemembreRepository.save(rolemembre);
        membreppaf.setRolemembre(rolemembre);
        return membreppaf;
    }

    @Inject
    private RolemembreRepository rolemembreRepository;
    @Inject
    private RolemembreGenerator rolemembreGenerator;
}