/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Rolemembre;
import com.eldoraludo.ppafgestion.repository.RolemembreRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.RolemembreDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on RolemembreRepositoryImpl
 */
public class RolemembreRepositoryImplTest {

    private RolemembreRepositoryImpl rolemembreRepositoryImpl;
    private RolemembreDao rolemembreDao;

    @Before
    public void setUp() {
        // called before each test.
        rolemembreRepositoryImpl = new RolemembreRepositoryImpl();
        rolemembreDao = mock(RolemembreDao.class);
        rolemembreRepositoryImpl.setRolemembreDao(rolemembreDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Rolemembre none = null;

        when(rolemembreDao.findUniqueOrNone(any(Rolemembre.class), any(SearchParameters.class))).thenReturn(none);

        Rolemembre result = rolemembreRepositoryImpl.findUniqueOrNone(new Rolemembre());

        assertThat(result).isNull();
        verify(rolemembreDao, times(1)).findUniqueOrNone(any(Rolemembre.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Rolemembre unique = new Rolemembre();

        when(rolemembreDao.findUniqueOrNone(any(Rolemembre.class), any(SearchParameters.class))).thenReturn(unique);

        Rolemembre result = rolemembreRepositoryImpl.findUniqueOrNone(new Rolemembre());

        assertThat(result).isNotNull();
        verify(rolemembreDao, times(1)).findUniqueOrNone(any(Rolemembre.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(rolemembreDao.findUniqueOrNone(any(Rolemembre.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        rolemembreRepositoryImpl.findUniqueOrNone(new Rolemembre());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(rolemembreDao.findUnique(any(Rolemembre.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        rolemembreRepositoryImpl.findUnique(new Rolemembre());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Rolemembre unique = new Rolemembre();

        when(rolemembreDao.findUnique(any(Rolemembre.class), any(SearchParameters.class))).thenReturn(unique);

        Rolemembre result = rolemembreRepositoryImpl.findUnique(new Rolemembre());

        assertThat(result).isNotNull();
        verify(rolemembreDao, times(1)).findUnique(any(Rolemembre.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(rolemembreDao.findUnique(any(Rolemembre.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        rolemembreRepositoryImpl.findUnique(new Rolemembre());
    }
}