/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Suividulieudedepot;
import com.eldoraludo.ppafgestion.repository.SuividulieudedepotRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.SuividulieudedepotDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on SuividulieudedepotRepositoryImpl
 */
public class SuividulieudedepotRepositoryImplTest {

    private SuividulieudedepotRepositoryImpl suividulieudedepotRepositoryImpl;
    private SuividulieudedepotDao suividulieudedepotDao;

    @Before
    public void setUp() {
        // called before each test.
        suividulieudedepotRepositoryImpl = new SuividulieudedepotRepositoryImpl();
        suividulieudedepotDao = mock(SuividulieudedepotDao.class);
        suividulieudedepotRepositoryImpl.setSuividulieudedepotDao(suividulieudedepotDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Suividulieudedepot none = null;

        when(suividulieudedepotDao.findUniqueOrNone(any(Suividulieudedepot.class), any(SearchParameters.class))).thenReturn(none);

        Suividulieudedepot result = suividulieudedepotRepositoryImpl.findUniqueOrNone(new Suividulieudedepot());

        assertThat(result).isNull();
        verify(suividulieudedepotDao, times(1)).findUniqueOrNone(any(Suividulieudedepot.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Suividulieudedepot unique = new Suividulieudedepot();

        when(suividulieudedepotDao.findUniqueOrNone(any(Suividulieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Suividulieudedepot result = suividulieudedepotRepositoryImpl.findUniqueOrNone(new Suividulieudedepot());

        assertThat(result).isNotNull();
        verify(suividulieudedepotDao, times(1)).findUniqueOrNone(any(Suividulieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(suividulieudedepotDao.findUniqueOrNone(any(Suividulieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        suividulieudedepotRepositoryImpl.findUniqueOrNone(new Suividulieudedepot());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(suividulieudedepotDao.findUnique(any(Suividulieudedepot.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        suividulieudedepotRepositoryImpl.findUnique(new Suividulieudedepot());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Suividulieudedepot unique = new Suividulieudedepot();

        when(suividulieudedepotDao.findUnique(any(Suividulieudedepot.class), any(SearchParameters.class))).thenReturn(unique);

        Suividulieudedepot result = suividulieudedepotRepositoryImpl.findUnique(new Suividulieudedepot());

        assertThat(result).isNotNull();
        verify(suividulieudedepotDao, times(1)).findUnique(any(Suividulieudedepot.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(suividulieudedepotDao.findUnique(any(Suividulieudedepot.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        suividulieudedepotRepositoryImpl.findUnique(new Suividulieudedepot());
    }
}