/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import java.util.Date;
import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Lieudedepot;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.domain.Suividulieudedepot;
import com.eldoraludo.ppafgestion.repository.LieudedepotGenerator;
import com.eldoraludo.ppafgestion.repository.LieudedepotRepository;
import com.eldoraludo.ppafgestion.repository.MembreppafGenerator;
import com.eldoraludo.ppafgestion.repository.MembreppafRepository;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class SuividulieudedepotGenerator {

    /**
     * Returns a new Suividulieudedepot instance filled with random values.
     */
    public Suividulieudedepot getSuividulieudedepot() {
        Suividulieudedepot suividulieudedepot = new Suividulieudedepot();

        // simple attributes follows
        suividulieudedepot.setDate(new Date());
        suividulieudedepot.setNote("a");
        // mandatory relation
        Membreppaf membreppaf = membreppafGenerator.getMembreppaf();
        membreppafRepository.save(membreppaf);
        suividulieudedepot.setMembreppaf(membreppaf);
        // mandatory relation
        Lieudedepot lieudedepot = lieudedepotGenerator.getLieudedepot();
        lieudedepotRepository.save(lieudedepot);
        suividulieudedepot.setLieudedepot(lieudedepot);
        return suividulieudedepot;
    }

    @Inject
    private MembreppafRepository membreppafRepository;
    @Inject
    private MembreppafGenerator membreppafGenerator;
    @Inject
    private LieudedepotRepository lieudedepotRepository;
    @Inject
    private LieudedepotGenerator lieudedepotGenerator;
}