/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Suivicontact;
import com.eldoraludo.ppafgestion.repository.SuivicontactRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.SuivicontactDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on SuivicontactRepositoryImpl
 */
public class SuivicontactRepositoryImplTest {

    private SuivicontactRepositoryImpl suivicontactRepositoryImpl;
    private SuivicontactDao suivicontactDao;

    @Before
    public void setUp() {
        // called before each test.
        suivicontactRepositoryImpl = new SuivicontactRepositoryImpl();
        suivicontactDao = mock(SuivicontactDao.class);
        suivicontactRepositoryImpl.setSuivicontactDao(suivicontactDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Suivicontact none = null;

        when(suivicontactDao.findUniqueOrNone(any(Suivicontact.class), any(SearchParameters.class))).thenReturn(none);

        Suivicontact result = suivicontactRepositoryImpl.findUniqueOrNone(new Suivicontact());

        assertThat(result).isNull();
        verify(suivicontactDao, times(1)).findUniqueOrNone(any(Suivicontact.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Suivicontact unique = new Suivicontact();

        when(suivicontactDao.findUniqueOrNone(any(Suivicontact.class), any(SearchParameters.class))).thenReturn(unique);

        Suivicontact result = suivicontactRepositoryImpl.findUniqueOrNone(new Suivicontact());

        assertThat(result).isNotNull();
        verify(suivicontactDao, times(1)).findUniqueOrNone(any(Suivicontact.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(suivicontactDao.findUniqueOrNone(any(Suivicontact.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        suivicontactRepositoryImpl.findUniqueOrNone(new Suivicontact());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(suivicontactDao.findUnique(any(Suivicontact.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        suivicontactRepositoryImpl.findUnique(new Suivicontact());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Suivicontact unique = new Suivicontact();

        when(suivicontactDao.findUnique(any(Suivicontact.class), any(SearchParameters.class))).thenReturn(unique);

        Suivicontact result = suivicontactRepositoryImpl.findUnique(new Suivicontact());

        assertThat(result).isNotNull();
        verify(suivicontactDao, times(1)).findUnique(any(Suivicontact.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(suivicontactDao.findUnique(any(Suivicontact.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        suivicontactRepositoryImpl.findUnique(new Suivicontact());
    }
}