/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Named;
import javax.inject.Singleton;
import com.eldoraludo.ppafgestion.domain.Utilisateur;
import com.eldoraludo.ppafgestion.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@SuppressWarnings("unused")
@Named
@Singleton
public class UtilisateurGenerator {

    /**
     * Returns a new Utilisateur instance filled with random values.
     */
    public Utilisateur getUtilisateur() {
        Utilisateur utilisateur = new Utilisateur();

        // simple attributes follows
        utilisateur.setUsername("aaaa");
        utilisateur.setPassword("a");
        utilisateur.setEmail("dummy@dummy.com");
        utilisateur.setRue("a");
        utilisateur.setVille("a");
        utilisateur.setCodepostal("a");
        utilisateur.setInfosuppl("a");
        utilisateur.setActif(true);
        return utilisateur;
    }

}