/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/service/ServiceImplTest.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import javax.persistence.NonUniqueResultException;
import javax.persistence.NoResultException;

import org.junit.Before;
import org.junit.Test;

import com.eldoraludo.ppafgestion.domain.Utilisateur;
import com.eldoraludo.ppafgestion.repository.UtilisateurRepositoryImpl;
import com.eldoraludo.ppafgestion.dao.UtilisateurDao;
import com.eldoraludo.ppafgestion.dao.support.SearchParameters;

/**
 * Unit test on UtilisateurRepositoryImpl
 */
public class UtilisateurRepositoryImplTest {

    private UtilisateurRepositoryImpl utilisateurRepositoryImpl;
    private UtilisateurDao utilisateurDao;

    @Before
    public void setUp() {
        // called before each test.
        utilisateurRepositoryImpl = new UtilisateurRepositoryImpl();
        utilisateurDao = mock(UtilisateurDao.class);
        utilisateurRepositoryImpl.setUtilisateurDao(utilisateurDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        Utilisateur none = null;

        when(utilisateurDao.findUniqueOrNone(any(Utilisateur.class), any(SearchParameters.class))).thenReturn(none);

        Utilisateur result = utilisateurRepositoryImpl.findUniqueOrNone(new Utilisateur());

        assertThat(result).isNull();
        verify(utilisateurDao, times(1)).findUniqueOrNone(any(Utilisateur.class), any(SearchParameters.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        Utilisateur unique = new Utilisateur();

        when(utilisateurDao.findUniqueOrNone(any(Utilisateur.class), any(SearchParameters.class))).thenReturn(unique);

        Utilisateur result = utilisateurRepositoryImpl.findUniqueOrNone(new Utilisateur());

        assertThat(result).isNotNull();
        verify(utilisateurDao, times(1)).findUniqueOrNone(any(Utilisateur.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        when(utilisateurDao.findUniqueOrNone(any(Utilisateur.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        utilisateurRepositoryImpl.findUniqueOrNone(new Utilisateur());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void testFindUniqueCaseNone() {
        when(utilisateurDao.findUnique(any(Utilisateur.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        utilisateurRepositoryImpl.findUnique(new Utilisateur());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        Utilisateur unique = new Utilisateur();

        when(utilisateurDao.findUnique(any(Utilisateur.class), any(SearchParameters.class))).thenReturn(unique);

        Utilisateur result = utilisateurRepositoryImpl.findUnique(new Utilisateur());

        assertThat(result).isNotNull();
        verify(utilisateurDao, times(1)).findUnique(any(Utilisateur.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void testFindUniqueCaseMultiple() {
        when(utilisateurDao.findUnique(any(Utilisateur.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        utilisateurRepositoryImpl.findUnique(new Utilisateur());
    }
}