/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.eldoraludo.ppafgestion.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafgestion.domain.Contact;
import com.eldoraludo.ppafgestion.repository.ContactGenerator;
import com.eldoraludo.ppafgestion.dao.ContactDao;

/**
 * Integration test on ContactDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class ContactDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(ContactDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private ContactDao contactDao;

    @Inject
    private ContactGenerator contactGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Contact contact = contactGenerator.getContact();

        // add it to a Set before saving (force equals/hashcode)
        Set<Contact> set = newHashSet(contact, contact);
        assertThat(set).hasSize(1);

        contactDao.save(contact);
        entityManager.flush();

        // reload it from cache and check equality
        Contact model = new Contact();
        model.setId(contact.getId());
        assertThat(contact).isEqualTo(contactDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(contact.getId()).isEqualTo(contactDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(contact).isNotEqualTo(contactDao.get(model));
    }
}