/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.eldoraludo.ppafgestion.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafgestion.domain.Itemlieudedepot;
import com.eldoraludo.ppafgestion.repository.ItemlieudedepotGenerator;
import com.eldoraludo.ppafgestion.dao.ItemlieudedepotDao;

/**
 * Integration test on ItemlieudedepotDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class ItemlieudedepotDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(ItemlieudedepotDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private ItemlieudedepotDao itemlieudedepotDao;

    @Inject
    private ItemlieudedepotGenerator itemlieudedepotGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Itemlieudedepot itemlieudedepot = itemlieudedepotGenerator.getItemlieudedepot();

        // add it to a Set before saving (force equals/hashcode)
        Set<Itemlieudedepot> set = newHashSet(itemlieudedepot, itemlieudedepot);
        assertThat(set).hasSize(1);

        itemlieudedepotDao.save(itemlieudedepot);
        entityManager.flush();

        // reload it from cache and check equality
        Itemlieudedepot model = new Itemlieudedepot();
        model.setId(itemlieudedepot.getId());
        assertThat(itemlieudedepot).isEqualTo(itemlieudedepotDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(itemlieudedepot.getId()).isEqualTo(itemlieudedepotDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(itemlieudedepot).isNotEqualTo(itemlieudedepotDao.get(model));
    }
}