/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.eldoraludo.ppafgestion.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafgestion.domain.Suivicontact;
import com.eldoraludo.ppafgestion.repository.SuivicontactGenerator;
import com.eldoraludo.ppafgestion.dao.SuivicontactDao;

/**
 * Integration test on SuivicontactDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SuivicontactDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(SuivicontactDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SuivicontactDao suivicontactDao;

    @Inject
    private SuivicontactGenerator suivicontactGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Suivicontact suivicontact = suivicontactGenerator.getSuivicontact();

        // add it to a Set before saving (force equals/hashcode)
        Set<Suivicontact> set = newHashSet(suivicontact, suivicontact);
        assertThat(set).hasSize(1);

        suivicontactDao.save(suivicontact);
        entityManager.flush();

        // reload it from cache and check equality
        Suivicontact model = new Suivicontact();
        model.setId(suivicontact.getId());
        assertThat(suivicontact).isEqualTo(suivicontactDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(suivicontact.getId()).isEqualTo(suivicontactDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(suivicontact).isNotEqualTo(suivicontactDao.get(model));
    }
}