/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/test/java/dao/DaoImplIT.e.vm.java
 */
package com.eldoraludo.ppafgestion.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.*;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.eldoraludo.ppafgestion.domain.Utilisateur;
import com.eldoraludo.ppafgestion.repository.UtilisateurGenerator;
import com.eldoraludo.ppafgestion.dao.UtilisateurDao;

/**
 * Integration test on UtilisateurDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UtilisateurDaoImplIT {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UtilisateurDaoImplIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private UtilisateurDao utilisateurDao;

    @Inject
    private UtilisateurGenerator utilisateurGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Utilisateur utilisateur = utilisateurGenerator.getUtilisateur();

        // add it to a Set before saving (force equals/hashcode)
        Set<Utilisateur> set = newHashSet(utilisateur, utilisateur);
        assertThat(set).hasSize(1);

        utilisateurDao.save(utilisateur);
        entityManager.flush();

        // reload it from cache and check equality
        Utilisateur model = new Utilisateur();
        model.setId(utilisateur.getId());
        assertThat(utilisateur).isEqualTo(utilisateurDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(utilisateur.getId()).isEqualTo(utilisateurDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(utilisateur).isNotEqualTo(utilisateurDao.get(model));
    }
}