/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/converter/EntityConverter.e.vm.java
 */
package com.eldoraludo.ppafgestion.web.converter.domain;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.repository.ItemlieudestockageRepository;
import com.eldoraludo.ppafgestion.web.converter.GenericJsfConverter;

/**
 * Responsible for creating Itemlieudestockage JSF converters.
 * Each converter provides a 'print' method to convert an entity instance to a friendly string representation (readable by humans...).
 */
@Component
public class ItemlieudestockageConverter extends GenericJsfConverter<Itemlieudestockage, Integer> {
    @Inject
    public ItemlieudestockageConverter(ItemlieudestockageRepository itemlieudestockageRepository) {
        super(itemlieudestockageRepository, Integer.class);
    }

    @Override
    public String print(Itemlieudestockage itemlieudestockage) {
        return itemlieudestockage == null ? "" : "" + itemlieudestockage.getNote();
    }
}