/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/support/EntitySelectors.p.vm.java
 */
package com.eldoraludo.ppafgestion.dao.support;

import javax.persistence.metamodel.SingularAttribute;
import com.eldoraludo.ppafgestion.domain.Contact;
import com.eldoraludo.ppafgestion.domain.Item;
import com.eldoraludo.ppafgestion.domain.Itemlieudedepot;
import com.eldoraludo.ppafgestion.domain.Itemlieudestockage;
import com.eldoraludo.ppafgestion.domain.Lieudedepot;
import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.domain.Role;
import com.eldoraludo.ppafgestion.domain.Rolemembre;
import com.eldoraludo.ppafgestion.domain.Suivicontact;
import com.eldoraludo.ppafgestion.domain.Suividulieudedepot;
import com.eldoraludo.ppafgestion.domain.Utilisateur;

/**
 * Convenient type safe {@link EntitySelector}s. 
 */
@SuppressWarnings("serial")
public class EntitySelectors {

    public static class ContactSelector<E> extends EntitySelector<E, Contact, Integer> {
        public ContactSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> ContactSelector<E> newContactSelector(SingularAttribute<E, Integer> field) {
            return new ContactSelector<E>(field);
        }
    }

    public static class ItemSelector<E> extends EntitySelector<E, Item, Integer> {
        public ItemSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> ItemSelector<E> newItemSelector(SingularAttribute<E, Integer> field) {
            return new ItemSelector<E>(field);
        }
    }

    public static class ItemlieudedepotSelector<E> extends EntitySelector<E, Itemlieudedepot, Integer> {
        public ItemlieudedepotSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> ItemlieudedepotSelector<E> newItemlieudedepotSelector(SingularAttribute<E, Integer> field) {
            return new ItemlieudedepotSelector<E>(field);
        }
    }

    public static class ItemlieudestockageSelector<E> extends EntitySelector<E, Itemlieudestockage, Integer> {
        public ItemlieudestockageSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> ItemlieudestockageSelector<E> newItemlieudestockageSelector(SingularAttribute<E, Integer> field) {
            return new ItemlieudestockageSelector<E>(field);
        }
    }

    public static class LieudedepotSelector<E> extends EntitySelector<E, Lieudedepot, Integer> {
        public LieudedepotSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> LieudedepotSelector<E> newLieudedepotSelector(SingularAttribute<E, Integer> field) {
            return new LieudedepotSelector<E>(field);
        }
    }

    public static class LieudestockageSelector<E> extends EntitySelector<E, Lieudestockage, Integer> {
        public LieudestockageSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> LieudestockageSelector<E> newLieudestockageSelector(SingularAttribute<E, Integer> field) {
            return new LieudestockageSelector<E>(field);
        }
    }

    public static class MembreppafSelector<E> extends EntitySelector<E, Membreppaf, Integer> {
        public MembreppafSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> MembreppafSelector<E> newMembreppafSelector(SingularAttribute<E, Integer> field) {
            return new MembreppafSelector<E>(field);
        }
    }

    public static class RoleSelector<E> extends EntitySelector<E, Role, Integer> {
        public RoleSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> RoleSelector<E> newRoleSelector(SingularAttribute<E, Integer> field) {
            return new RoleSelector<E>(field);
        }
    }

    public static class RolemembreSelector<E> extends EntitySelector<E, Rolemembre, Integer> {
        public RolemembreSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> RolemembreSelector<E> newRolemembreSelector(SingularAttribute<E, Integer> field) {
            return new RolemembreSelector<E>(field);
        }
    }

    public static class SuivicontactSelector<E> extends EntitySelector<E, Suivicontact, Integer> {
        public SuivicontactSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> SuivicontactSelector<E> newSuivicontactSelector(SingularAttribute<E, Integer> field) {
            return new SuivicontactSelector<E>(field);
        }
    }

    public static class SuividulieudedepotSelector<E> extends EntitySelector<E, Suividulieudedepot, Integer> {
        public SuividulieudedepotSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> SuividulieudedepotSelector<E> newSuividulieudedepotSelector(SingularAttribute<E, Integer> field) {
            return new SuividulieudedepotSelector<E>(field);
        }
    }

    public static class UtilisateurSelector<E> extends EntitySelector<E, Utilisateur, Integer> {
        public UtilisateurSelector(SingularAttribute<E, Integer> field) {
            super(field);
        }

        public static <E> UtilisateurSelector<E> newUtilisateurSelector(SingularAttribute<E, Integer> field) {
            return new UtilisateurSelector<E>(field);
        }
    }
}