/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Contact;
import com.eldoraludo.ppafgestion.dao.ContactDao;

/**
 * Default implementation of the {@link ContactRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see ContactRepository
 */
@Named("contactRepository")
@Singleton
public class ContactRepositoryImpl extends RepositoryImpl<Contact, Integer> implements ContactRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(ContactRepositoryImpl.class);

    protected ContactDao contactDao;

    @Inject
    public void setContactDao(ContactDao contactDao) {
        this.contactDao = contactDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Contact, Integer> getDao() {
        return contactDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contact getNew() {
        return new Contact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Contact getNewWithDefaults() {
        Contact result = getNew();
        result.initDefaultValues();
        return result;
    }

}