/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Item;
import com.eldoraludo.ppafgestion.dao.ItemDao;

/**
 * Default implementation of the {@link ItemRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see ItemRepository
 */
@Named("itemRepository")
@Singleton
public class ItemRepositoryImpl extends RepositoryImpl<Item, Integer> implements ItemRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(ItemRepositoryImpl.class);

    protected ItemDao itemDao;

    @Inject
    public void setItemDao(ItemDao itemDao) {
        this.itemDao = itemDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Item, Integer> getDao() {
        return itemDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Item getNew() {
        return new Item();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Item getNewWithDefaults() {
        Item result = getNew();
        result.initDefaultValues();
        return result;
    }

}