/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Itemlieudedepot;
import com.eldoraludo.ppafgestion.dao.ItemlieudedepotDao;

/**
 * Default implementation of the {@link ItemlieudedepotRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see ItemlieudedepotRepository
 */
@Named("itemlieudedepotRepository")
@Singleton
public class ItemlieudedepotRepositoryImpl extends RepositoryImpl<Itemlieudedepot, Integer> implements ItemlieudedepotRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(ItemlieudedepotRepositoryImpl.class);

    protected ItemlieudedepotDao itemlieudedepotDao;

    @Inject
    public void setItemlieudedepotDao(ItemlieudedepotDao itemlieudedepotDao) {
        this.itemlieudedepotDao = itemlieudedepotDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Itemlieudedepot, Integer> getDao() {
        return itemlieudedepotDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Itemlieudedepot getNew() {
        return new Itemlieudedepot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Itemlieudedepot getNewWithDefaults() {
        Itemlieudedepot result = getNew();
        result.initDefaultValues();
        return result;
    }

}