/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Lieudestockage;
import com.eldoraludo.ppafgestion.dao.LieudestockageDao;

/**
 * Default implementation of the {@link LieudestockageRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see LieudestockageRepository
 */
@Named("lieudestockageRepository")
@Singleton
public class LieudestockageRepositoryImpl extends RepositoryImpl<Lieudestockage, Integer> implements LieudestockageRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(LieudestockageRepositoryImpl.class);

    protected LieudestockageDao lieudestockageDao;

    @Inject
    public void setLieudestockageDao(LieudestockageDao lieudestockageDao) {
        this.lieudestockageDao = lieudestockageDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Lieudestockage, Integer> getDao() {
        return lieudestockageDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Lieudestockage getNew() {
        return new Lieudestockage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Lieudestockage getNewWithDefaults() {
        Lieudestockage result = getNew();
        result.initDefaultValues();
        return result;
    }

}