/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.dao.MembreppafDao;

/**
 * Default implementation of the {@link MembreppafRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see MembreppafRepository
 */
@Named("membreppafRepository")
@Singleton
public class MembreppafRepositoryImpl extends RepositoryImpl<Membreppaf, Integer> implements MembreppafRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(MembreppafRepositoryImpl.class);

    protected MembreppafDao membreppafDao;

    @Inject
    public void setMembreppafDao(MembreppafDao membreppafDao) {
        this.membreppafDao = membreppafDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Membreppaf, Integer> getDao() {
        return membreppafDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Membreppaf getNew() {
        return new Membreppaf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Membreppaf getNewWithDefaults() {
        Membreppaf result = getNew();
        result.initDefaultValues();
        return result;
    }

}