/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Suividulieudedepot;
import com.eldoraludo.ppafgestion.dao.SuividulieudedepotDao;

/**
 * Default implementation of the {@link SuividulieudedepotRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see SuividulieudedepotRepository
 */
@Named("suividulieudedepotRepository")
@Singleton
public class SuividulieudedepotRepositoryImpl extends RepositoryImpl<Suividulieudedepot, Integer> implements SuividulieudedepotRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(SuividulieudedepotRepositoryImpl.class);

    protected SuividulieudedepotDao suividulieudedepotDao;

    @Inject
    public void setSuividulieudedepotDao(SuividulieudedepotDao suividulieudedepotDao) {
        this.suividulieudedepotDao = suividulieudedepotDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Suividulieudedepot, Integer> getDao() {
        return suividulieudedepotDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Suividulieudedepot getNew() {
        return new Suividulieudedepot();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Suividulieudedepot getNewWithDefaults() {
        Suividulieudedepot result = getNew();
        result.initDefaultValues();
        return result;
    }

}