/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/RepositoryImpl.e.vm.java
 */
package com.eldoraludo.ppafgestion.repository;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import com.eldoraludo.ppafgestion.dao.support.GenericDao;
import com.eldoraludo.ppafgestion.repository.support.RepositoryImpl;
import com.eldoraludo.ppafgestion.domain.Utilisateur;
import com.eldoraludo.ppafgestion.dao.UtilisateurDao;

/**
 * Default implementation of the {@link UtilisateurRepository} interface.
 * Note: you may use multiple DAO from this layer.
 * @see UtilisateurRepository
 */
@Named("utilisateurRepository")
@Singleton
public class UtilisateurRepositoryImpl extends RepositoryImpl<Utilisateur, Integer> implements UtilisateurRepository {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UtilisateurRepositoryImpl.class);

    protected UtilisateurDao utilisateurDao;

    @Inject
    public void setUtilisateurDao(UtilisateurDao utilisateurDao) {
        this.utilisateurDao = utilisateurDao;
    }

    /**
     * Dao getter used by the {@link RepositoryImpl}.
     */
    @Override
    public GenericDao<Utilisateur, Integer> getDao() {
        return utilisateurDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Utilisateur getNew() {
        return new Utilisateur();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Utilisateur getNewWithDefaults() {
        Utilisateur result = getNew();
        result.initDefaultValues();
        return result;
    }

}