/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.eldoraludo.ppafgestion.domain;

import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import com.eldoraludo.ppafgestion.domain.PersistableHashBuilder;
import com.google.common.base.Objects;

@Entity
@Table(name = "LIEUDEDEPOT")
@Cache(usage = NONSTRICT_READ_WRITE)
public class Lieudedepot implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Lieudedepot.class);

    // Raw attributes
    private Integer id; // pk
    private String numerotelephone1;
    private String numerotelephone2;
    private String rue;
    private String ville;
    private String codepostal;
    private String infosuppl;
    private String type;

    // ---------------------------
    // Constructors
    // ---------------------------

    public Lieudedepot() {
    }

    public Lieudedepot(Integer primaryKey) {
        setId(primaryKey);
    }

    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [numerotelephone1] ------------------------

    @Size(max = 100)
    @Column(name = "NUMEROTELEPHONE1", length = 100)
    public String getNumerotelephone1() {
        return numerotelephone1;
    }

    public void setNumerotelephone1(String numerotelephone1) {
        this.numerotelephone1 = numerotelephone1;
    }

    // -- [numerotelephone2] ------------------------

    @Size(max = 100)
    @Column(name = "NUMEROTELEPHONE2", length = 100)
    public String getNumerotelephone2() {
        return numerotelephone2;
    }

    public void setNumerotelephone2(String numerotelephone2) {
        this.numerotelephone2 = numerotelephone2;
    }

    // -- [rue] ------------------------

    @Size(max = 100)
    @Column(name = "RUE", length = 100)
    public String getRue() {
        return rue;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    // -- [ville] ------------------------

    @Size(max = 100)
    @Column(name = "VILLE", length = 100)
    public String getVille() {
        return ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    // -- [codepostal] ------------------------

    @Size(max = 100)
    @Column(name = "CODEPOSTAL", length = 100)
    public String getCodepostal() {
        return codepostal;
    }

    public void setCodepostal(String codepostal) {
        this.codepostal = codepostal;
    }

    // -- [infosuppl] ------------------------

    @Size(max = 2147483647)
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "INFOSUPPL")
    @Lob
    public String getInfosuppl() {
        return infosuppl;
    }

    public void setInfosuppl(String infosuppl) {
        this.infosuppl = infosuppl;
    }

    // -- [type] ------------------------

    @Size(max = 100)
    @Column(name = "`TYPE`", length = 100)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Lieudedepot && hashCode() == other.hashCode());
    }

    private PersistableHashBuilder persistableHashBuilder = new PersistableHashBuilder();

    @Override
    public int hashCode() {
        return persistableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Lieudedepot instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("numerotelephone1", getNumerotelephone1()) //
                .add("numerotelephone2", getNumerotelephone2()) //
                .add("rue", getRue()) //
                .add("ville", getVille()) //
                .add("codepostal", getCodepostal()) //
                .add("infosuppl", getInfosuppl()) //
                .add("type", getType()) //
                .toString();
    }
}