/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.eldoraludo.ppafgestion.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.eldoraludo.ppafgestion.domain.Rolemembre;

@StaticMetamodel(Membreppaf.class)
public abstract class Membreppaf_ {

    // Raw attributes
    public static volatile SingularAttribute<Membreppaf, Integer> id;
    public static volatile SingularAttribute<Membreppaf, String> nom;
    public static volatile SingularAttribute<Membreppaf, String> prenom;
    public static volatile SingularAttribute<Membreppaf, String> numerotelephone1;
    public static volatile SingularAttribute<Membreppaf, String> numerotelephone2;
    public static volatile SingularAttribute<Membreppaf, String> email;
    public static volatile SingularAttribute<Membreppaf, Boolean> actif;
    public static volatile SingularAttribute<Membreppaf, String> note;
    public static volatile SingularAttribute<Membreppaf, String> rue;
    public static volatile SingularAttribute<Membreppaf, String> ville;
    public static volatile SingularAttribute<Membreppaf, String> codepostal;
    public static volatile SingularAttribute<Membreppaf, String> infosuppl;

    // Technical attributes for query by example
    public static volatile SingularAttribute<Membreppaf, Integer> rolemembreId;

    // Many to one
    public static volatile SingularAttribute<Membreppaf, Rolemembre> rolemembre;
}