/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity_.e.vm.java
 */
package com.eldoraludo.ppafgestion.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import com.eldoraludo.ppafgestion.domain.Membreppaf;
import com.eldoraludo.ppafgestion.domain.Role;

@StaticMetamodel(Utilisateur.class)
public abstract class Utilisateur_ {

    // Raw attributes
    public static volatile SingularAttribute<Utilisateur, Integer> id;
    public static volatile SingularAttribute<Utilisateur, String> username;
    public static volatile SingularAttribute<Utilisateur, String> password;
    public static volatile SingularAttribute<Utilisateur, String> email;
    public static volatile SingularAttribute<Utilisateur, String> rue;
    public static volatile SingularAttribute<Utilisateur, String> ville;
    public static volatile SingularAttribute<Utilisateur, String> codepostal;
    public static volatile SingularAttribute<Utilisateur, String> infosuppl;
    public static volatile SingularAttribute<Utilisateur, Boolean> actif;

    // Technical attributes for query by example
    public static volatile SingularAttribute<Utilisateur, Integer> membreppafId;

    // Many to one
    public static volatile SingularAttribute<Utilisateur, Membreppaf> membreppaf;

    // Many to many
    public static volatile ListAttribute<Utilisateur, Role> roles;
}